# Generated by Django 5.0.7 on 2024-08-13 09:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_blog_image_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
