# Generated by Django 5.0.7 on 2024-08-17 05:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
